kind: Service
apiVersion: v1
metadata:
  name: capsule-demo-app-service
spec:
  selector:
    app: capsule-demo-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 38080